apiVersion: v1
kind: Pod
metadata:
  name: gpu-one-rook-hk-ii
spec:
  containers:
  - name: gpu-container
    image: pytorch/pytorch
    imagePullPolicy: Always
    args: ["sleep", "36500000"]
    resources:
      limits:
        nvidia.com/gpu: 1
    volumeMounts:
      - mountPath: /pervol-ii
        name: pervol-ii
  restartPolicy: Never
  volumes:
    - name: pervol-ii
      persistentVolumeClaim:
        claimName: pervol-ii
