apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pervol
spec:
  storageClassName: rook-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 150Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: gpu-one-rook-hk
spec:
  containers:
  - name: gpu-container
    image: hkashyap/evolverl
    imagePullPolicy: Always
    args: ["sleep", "36500000"]
    resources:
      limits:
        nvidia.com/gpu: 1
    volumeMounts:
      - mountPath: /pervol
        name: pervol
  restartPolicy: Never
  volumes:
    - name: pervol
      persistentVolumeClaim:
        claimName: pervol
