apiVersion: v1
kind: Pod
metadata:
  name: gpu-one-rook-hk
spec:
  containers:
  - name: gpu-container
    image: hkashyap/evolverl
    imagePullPolicy: Always
    args: ["sleep", "36500000"]
    resources:
      limits:
        nvidia.com/gpu: 1
        memory: 16Gi
      requests:
        nvidia.com/gpu: 1
        memory: 16Gi
    volumeMounts:
      - mountPath: /pervol
        name: pervol
  restartPolicy: Never
  volumes:
    - name: pervol
      persistentVolumeClaim:
        claimName: pervol
