apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod-example-pt
spec:
  containers:
  - name: gpu-container
    image: uetchy/machinelearning
    imagePullPolicy: Always
    args: ["sleep", "36500000"]
    resources:
      limits:
        nvidia.com/gpu: 1
    volumeMounts:
      - mountPath: /dev/shm
        name: dshm
  volumes:
    - name: dshm
      emptyDir:
        medium: Memory
